# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
matrix:
  exclude:
    # Python/Django combinations that aren't officially supported
    - { python: 3.6, env: DJANGO=1.8 }
    - { python: 3.3, env: DJANGO=1.9 }
    - { python: 3.6, env: DJANGO=1.9 }
    - { python: 3.3, env: DJANGO=1.10 }
    - { python: 3.6, env: DJANGO=1.10 }
    - { python: 3.3, env: DJANGO=1.11 }
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements_test.txt
  - pip install tox-travis

# command to run tests using coverage, e.g. python setup.py test
script:
  - tox
#
#after_success:
#  - codecov -e TOX_ENV
